language: rust
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - ./cardano-c/test.sh
matrix:
  include:
    - rust: stable
    - rust: nightly
    - rust: nightly
      env:  TARGET="wasm32-unknown-unknown"
      before_script:
        - rustup target add ${TARGET} --toolchain nightly
      script:
        - cargo  +nightly build --target ${TARGET} --release --verbose  --package cryptoxide --package cardano --package protocol
