language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
#matrix:
#  allow_failures:
#    - rust: nightly
before_install:
  - nvm install 8.2.1
before_script:
  - npm install
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - ./build
  - npm run test
