[package]
name = "cardano"
version = "0.1.0"
authors = ["vincent.hanquez@iohk.io", "nicolas.diprima@iohk.io"]
license = "MIT"
description = "A Rust implementation of cardano types and wallet"
keywords = [ "Cardano", "Wallet", "Crypto" ]

[build-dependencies]

[dependencies]
cryptoxide = { path = "../cryptoxide" }
cbor_event = { path = "../cbor_event" }

serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.4"
serde_json = "*"
unicode-normalization = "0.1.7"

[features]
default = []
with-bench = []
generic-serialization = ["serde", "serde_derive"]
