[package]
name = "storage"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]

[dependencies]
rcw = { path = "../rcw" }
wallet-crypto = { path = "../wallet-crypto" }
blockchain = { path = "../blockchain" }
rand = "0.4"
flate2 = "1.0.1"
