[package]
name = "storage"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>", "Nicolas Di Prima <nicolas.diprima@iohk.io>"]

[dependencies]
rcw = { path = "../rcw" }
cardano = { path = "../cardano" }
raw_cbor = { path = "../cbor" }
log = "*"
rand = "0.4"
flate2 = "1.0.1"
