[package]
name = "cardano-c"
version = "0.1.0"
authors = ["Vincent Hanquez <vincent.hanquez@iohk.io>", "Nicolas Di Prima <nicolas.diprima@iohk.io>", "The Rust-Crypto Project Developers"]

[lib]
crate-type = ["staticlib" ]

[dependencies]
cardano = { path = "../cardano" }
